FROM node:18-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY . .

# Expose Vite development server port
EXPOSE 5173

# Run development server
CMD ["npm", "run", "dev", "--", "--host"]
